//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Projection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projection()
        {
            this.Reservations = new HashSet<Reservation>();
            this.ReservedSeats = new HashSet<ReservedSeat>();
        }
    
        public int ProjectionId { get; set; }

        [Required(ErrorMessage = "Izaberite film koji se prikazuje!")]
        [Display(Name = "Film")]
        public int MovieId { get; set; }

        [Required(ErrorMessage = "Izaberite salu u kojoj se prikazuje film!")]
        [Display(Name = "Sala")]
        public int AuditoriumId { get; set; }

        [Required(ErrorMessage = "Unesite cijenu karte!")]
        [Display(Name = "Cijena karte")]
        public Nullable<decimal> TicketPrice { get; set; }

        [Required(ErrorMessage = "Unesite datum i vrijeme projekcije")]
        [Display(Name = "Datum i vrijeme")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual Movie Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedSeat> ReservedSeats { get; set; }
        public virtual Auditorium Auditorium { get; set; }
    }
}
