//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedSeat
    {
        public int ReservedSeatId { get; set; }
        public int ReservationId { get; set; }
        public int SeatId { get; set; }
        public int ProjectionId { get; set; }
    
        public virtual Projection Projection { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
