//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.ReservedSeats = new HashSet<ReservedSeat>();
        }
    
        public int ReservationId { get; set; }
        public int ProjectionId { get; set; }

        [Display(Name = "Broj karata")]
        public Nullable<int> NumberOfTickets { get; set; }

        [Display(Name = "Ukupna cijena")]
        public Nullable<decimal> TotalPrice { get; set; }

        [Display(Name = "Potvrđena")]
        public Nullable<bool> IsConfirmed { get; set; }

        [Display(Name = "Aktivna")]
        public Nullable<bool> IsActive { get; set; }

        public string UserId { get; set; }
        public Nullable<System.DateTime> ReservationTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
    
        public virtual Projection Projection { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedSeat> ReservedSeats { get; set; }
    }
}
