//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpecialOffer
    {
        public int OfferId { get; set; }

        [Required(ErrorMessage = "Unesite naziv ponude!")]
        [Display(Name = "Naziv ponude")]
        public string OfferName { get; set; }

        [Required]
        [Display(Name = "Unesite opis ponude")]
        public string Description { get; set; }

        [Display(Name = "Poster")]
        public string OfferImage { get; set; }
    }
}
